### ISSUE TITLE
Add ContentSizeCategoryMonitor

### ISSUE THREAD

**Issue by Descartess** [eBardX/XestiMonitors#13]
#### Feature Name 

* ContentSizeCategoryMonitor

#### Events

* `didChange(UIContentSizeCategory)` -- wraps `UIContentSizeCategoryDidChange` notification

#### Platform

* iOS/tvOS

**Comment by angiemugo** [comment]
I will take this one.

**Comment by eBardX** [comment]
@angiemugo Do you still plan to finish this up?

**Comment by angiemugo** [comment]
Whoa! The comments you made somehow flew right past me. Yes, I intend to. I will get that done by end of day today.

**Comment by angiemugo** [comment]
Hey @eBardX, one of my tests is failing. I have narrowed the problem down to how I am initialising my user info but I have no clue how to solve it. Could you take a look at it please?

**Comment by eBardX** [comment]
Sure @angiemugo. Make sure you have pushed up all your latest changes.
