### ISSUE TITLE
Add TableViewSelectionMonitor

### ISSUE THREAD

**Issue by Descartess** [eBardX/XestiMonitors#20]
#### Feature Name 

- TableViewSelectionMonitor

#### Events

- `didChange(UITableView)` -- wraps `UITableViewSelectionDidChange` notification

#### Platform

- iOS/tvOS

**Comment by rosemaina** [comment]
I will take this one

**Comment by eBardX** [comment]
@rosemaina Do you still plan to finish this up?

**Comment by rosemaina** [comment]
Yes.
I have done everything apart from removing the `pods` folder.

**Comment by rosemaina** [comment]
Hey John,

I keep getting this error in my build about my CocoaPod Installation which
I have not been able to eliminate

error: The sandbox is not in sync with the Podfile.lock. Run 'pod install'
or update your CocoaPods installation.
But I have silenced all the hound errors.

**Comment by eBardX** [comment]
@rosemaina 

Where are you seeing that error? When you build `XestiMonitors` or when you build `XestiMonitorsDemo`? If the latter, you can ignore. Rebuilding the demo app is _not_ necessary for the changes you are making. If the former, there should be no `Podfile.lock` (or `Podfile` for that matter) for the main `XestiMonitors` project.
