### ISSUE TITLE
Add UndoManagerMonitor

### ISSUE THREAD

**Issue by eBardX** [eBardX/XestiMonitors#41]
#### Feature Name 

- `UndoManagerMonitor` -- should live in `Foundation` folder

#### Events

- `checkpoint(UndoManager)` — wraps `NSUndoManagerCheckpoint` notification
- `didCloseUndoGroup(UndoManager)` — wraps `NSUndoManagerDidCloseUndoGroup` notification
- `didOpenUndoGroup(UndoManager)` — wraps `NSUndoManagerDidOpenUndoGroup` notification
- `didRedoChange(UndoManager)` — wraps `NSUndoManagerDidRedoChange` notification
- `didUndoChange(UndoManager)` — wraps `NSUndoManagerDidUndoChange` notification
- `willCloseUndoGroup(UndoManager)` — wraps `NSUndoManagerWillCloseUndoGroup` notification
- `willRedoChange(UndoManager)` — wraps `NSUndoManagerWillRedoChange` notification
- `willUndoChange(UndoManager)` — wraps `NSUndoManagerWillUndoChange` notification

#### Platform

iOS/macOS /tvOS/watchOS

**Comment by rosemaina** [comment]
I can take this one

**Comment by rosemaina** [comment]
@eBardX  Hello
I might longer than I expected to finish this, owing I have not yet started it. Maybe someone else could take up the task or if you don't mind I could submit it next week.
