### ISSUE TITLE
Add UserDefaultsMonitor

### ISSUE THREAD

**Issue by eBardX** [eBardX/XestiMonitors#44]
#### Feature Name 

- `UserDefaultsMonitor` -- should live in `Foundation` folder

#### Events

- `didChange(UserDefaults)` -- wraps `UserDefaults.didChangeNotification` notification
- `sizeLimitExceeded` -- wraps `UserDefaults.sizeLimitExceededNotification` notification

#### Platform

iOS/macOS/tvOS/watchOS

**Comment by eBardX** [comment]
@Descartess
**Note:** `didChange(UserDefaults)` looks to be very straightforward. The notifications wrapped by the other four events have vague documentation. It is not clear to me how those notifications are even generated in normal usage.

**Comment by Descartess** [comment]
Yes I am wondering what is the notification object for the other four events besides `didChange(UserDefaults)`

**Comment by eBardX** [comment]
My guess is that it would be an instance of `UserDefaults` in all cases. But I have no empirical evidence to back that up (yet).

**Comment by eBardX** [comment]
@Descartess 
I’m thinking it may sense to break this into two separate monitors: `UserDefaultsMonitor` and `UbiquitousUserDefaultsMonitor`. If you look at the Objective-C names of the notifications, you’ll find that 2 are prefixed with `NSUserDefaults*` and 3 are prefixed with `NSUbiquitousUserDefaults*`. Also note that only 1 notification is supported on macOS. No matter how you slice it, on macOS it makes no sense to have an `options` parameter. This will make for some ugly code, although perhaps slightly less ugly if we opt for 2 monitors instead of 1. What do you think?

**Comment by Descartess** [comment]
Yes, that is correct. Let me create a separate issue for that
