### ISSUE TITLE
Add ExtensionHostMonitor

### ISSUE THREAD

**Issue by eBardX** [eBardX/XestiMonitors#48]
#### Feature Name 

- `ExtensionHostMonitor` -- should live in `Foundation` folder

#### Events

- `didBecomeActive(NSExtensionContext)` -- wraps `NSExtensionHostDidBecomeActive` notification
- `didEnterBackground(NSExtensionContext)` -- wraps `NSExtensionHostDidEnterBackground` notification
- `willEnterForeground(NSExtensionContext)` -- wraps `NSExtensionHostWillEnterForeground` notification
- `willResignActive(NSExtensionContext)` -- wraps `NSExtensionHostWillResignActive` notification

#### Platform

iOS/tvOS/watchOS

**Comment by rosemaina** [comment]
I will take this one
