### ISSUE TITLE
Add UbiquitousUserDefaultsMonitor

### ISSUE THREAD

**Issue by Descartess** [eBardX/XestiMonitors#60]
#### Feature Name 
- `UbiquitousUserDefaultsMonitor ` -- should live in `Foundation` folder

#### Events

- `completedInitialCloudSync` -- wraps `UserDefaults.completedInitialCloudSyncNotification` notification
- `didChangeCloudAccounts` -- wraps `UserDefaults.didChangeCloudAccountsNotification` notification
- `noCloudAccount` -- wraps `UserDefaults.noCloudAccountNotification` notification

#### Platform
iOS /tvOS/watchOS

**Comment by eBardX** [comment]
`UserDefaults.sizeLimitExceededNotification` should be wrapped by `UserDefaultsMonitor` -- it has nothing to do with the cloud-based user defaults.

**Comment by rosemaina** [comment]
I can take this one

**Comment by eBardX** [comment]
It looks as though these remaining notifications are not actually sent anywhere in `Foundation` that I have been able to find. Therefore, I am closing this issue until such time as these notifications are actually supported.
