### ISSUE TITLE
MenuControllerMonitor implementation is incorrect

### ISSUE THREAD

**Issue by eBardX** [eBardX/XestiMonitors#72]
All calls to `observe` should pass `UIMenuController.shared` in `object` parameter.

####  Environment

iOS

**Comment by Descartess** [comment]
@eBardX  I am curious as to why should calls should pass `UIMenuController.shared` in `object` parameter

**Comment by eBardX** [comment]
@Descartess `UIMenuController()` creates a new instance, and therefore you would not be able to write unit tests against the monitor unless you introduced dependency injection (which is overkill here). Using the singleton instance of `UIMenuController.shared` alleviates that problem.
